import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif",
    padding: "clamp(1rem, 4vw, 2rem)",
    maxWidth: "1400px",
    margin: "0 auto",
    minHeight: "100vh",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "60vh",
    gap: "1rem",
  },
  spinner: {
    width: "48px",
    height: "48px",
    border: "4px solid #e0e0e0",
    borderTop: "4px solid #0052FF",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  loadingText: {
    color: "#666",
    fontSize: "1rem",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    marginBottom: "2rem",
    paddingBottom: "1.5rem",
    borderBottom: "2px solid var(--border-color)",
  },
  headerTitleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  logo: {
    height: "48px",
    width: "auto",
  },
  title: {
    margin: 0,
    fontSize: "clamp(1.5rem, 5vw, 2.5rem)",
    fontWeight: 700,
    background: "linear-gradient(135deg, #0052FF 0%, #00D4A1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  headerActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  headerBalance: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "0.25rem",
    padding: "0.5rem 1rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
  },
  headerBalanceLabel: {
    fontSize: "0.75rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  headerBalanceAmount: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#00D4A1",
    display: "flex",
    alignItems: "baseline",
    gap: "0.25rem",
  },
  userProfile: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "0.5rem 1rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
  },
  userAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    objectFit: "cover",
    flexShrink: 0,
  },
  userAvatarFallback: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#0052FF",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.875rem",
    fontWeight: 600,
    flexShrink: 0,
  },
  userName: {
    fontSize: "0.95rem",
    fontWeight: 500,
    color: "var(--text-primary)",
    maxWidth: "120px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  link: {
    color: "#0052FF",
    textDecoration: "none",
    fontWeight: 500,
    fontSize: "0.95rem",
    transition: "opacity 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  linkIcon: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
  },
  errorBanner: {
    background: "var(--error-bg)",
    color: "var(--error-text)",
    padding: "1rem 1.5rem",
    borderRadius: "8px",
    marginBottom: "1.5rem",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    border: "1px solid var(--error-border)",
  },
  dismiss: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    cursor: "pointer",
  },
  summaryCard: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    padding: "clamp(1.5rem, 4vw, 2rem)",
    borderRadius: "16px",
    marginBottom: "2rem",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
  },
  summaryLabel: {
    fontSize: "0.875rem",
    opacity: 0.9,
    marginBottom: "0.5rem",
    fontWeight: 500,
  },
  summaryAmount: {
    fontSize: "clamp(1.75rem, 5vw, 2.5rem)",
    fontWeight: 700,
  },
  section: {
    marginBottom: "2rem",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1rem",
    flexWrap: "wrap",
    gap: "1rem",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  tabs: {
    display: "flex",
    gap: "0.5rem",
    marginBottom: "2rem",
    borderBottom: "2px solid var(--border-color)",
  },
  tab: {
    padding: "0.75rem 1.5rem",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    background: "transparent",
    border: "none",
    borderBottom: "3px solid transparent",
    color: "var(--text-secondary)",
    transition: "color 0.2s, border-color 0.2s",
    marginBottom: "-2px",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  tabIcon: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
  },
  tabActive: {
    color: "#0052FF",
    borderBottomColor: "#0052FF",
  },
  tabContent: {
    display: "block",
  },
  tabContentHidden: {
    display: "none",
  },
  emptyCard: {
    background: "var(--bg-secondary)",
    padding: "4rem 2rem",
    borderRadius: "12px",
    textAlign: "center",
    boxShadow: "0 2px 8px var(--shadow)",
    color: "var(--text-primary)",
  },
  emptyIcon: {
    fontSize: "4rem",
    marginBottom: "1rem",
  },
  emptyTitle: {
    margin: "0 0 0.5rem 0",
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  emptyText: {
    color: "var(--text-secondary)",
    marginBottom: "1.5rem",
  },
  walletCard: {
    background: "var(--bg-secondary)",
    padding: "clamp(1rem, 3vw, 1.5rem)",
    borderRadius: "16px",
    boxShadow: "0 4px 12px var(--shadow)",
    border: "1px solid var(--border-light)",
    transition: "transform 0.2s, box-shadow 0.2s",
    color: "var(--text-primary)",
  },
  walletCardHeader: {
    marginBottom: "1.5rem",
  },
  walletInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  walletLabel: {
    fontSize: "0.75rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  walletAddressRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  walletAddress: {
    fontFamily: "monospace",
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  balanceSection: {
    padding: "1rem",
    background: "var(--bg-tertiary)",
    borderRadius: "12px",
    marginBottom: "1.5rem",
  },
  balanceLabel: {
    fontSize: "0.75rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "0.5rem",
  },
  balanceRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  balanceAmount: {
    display: "flex",
    alignItems: "baseline",
    gap: "0.5rem",
  },
  balanceValue: {
    fontSize: "1.75rem",
    fontWeight: 700,
    color: "#00D4A1",
  },
  balanceSymbol: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  walletActions: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: "0.75rem",
  },
  actionButton: {
    flex: "1 1 0",
    minWidth: "120px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    padding: "0.75rem 1rem",
    fontSize: "0.95rem",
    cursor: "pointer",
    background: "#0052FF",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontWeight: 600,
    transition: "background 0.2s, transform 0.1s",
  },
  iconButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0.5rem",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    borderRadius: "6px",
    color: "var(--text-secondary)",
    transition: "background 0.2s, color 0.2s",
  },
  button: {
    padding: "0.75rem 1.5rem",
    fontSize: "1rem",
    cursor: "pointer",
    background: "#0052FF",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontWeight: 600,
    transition: "background 0.2s, transform 0.1s",
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  buttonSecondary: {
    padding: "0.75rem 1.5rem",
    fontSize: "1rem",
    cursor: "pointer",
    background: "var(--bg-hover)",
    color: "var(--text-tertiary)",
    border: "none",
    borderRadius: "8px",
    fontWeight: 600,
    transition: "background 0.2s",
  },
  errorCard: {
    background: "var(--bg-secondary)",
    padding: "2rem",
    borderRadius: "12px",
    boxShadow: "0 4px 12px var(--shadow)",
    textAlign: "center",
    color: "var(--text-primary)",
  },
  errorIcon: {
    fontSize: "3rem",
    marginBottom: "1rem",
  },
  errorTitle: {
    margin: "0 0 0.5rem 0",
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "var(--error-text)",
  },
  errorMessage: {
    color: "var(--text-secondary)",
    marginBottom: "1.5rem",
  },
  modal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "var(--modal-overlay)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(4px)",
  },
  modalContent: {
    background: "var(--bg-secondary)",
    padding: "clamp(1rem, 4vw, 2rem)",
    borderRadius: "16px",
    maxWidth: "500px",
    width: "90%",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 20px 60px var(--shadow-hover)",
    color: "var(--text-primary)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
    paddingBottom: "1rem",
    borderBottom: "1px solid var(--border-light)",
  },
  modalTitle: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  closeButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0.5rem",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    borderRadius: "6px",
    color: "var(--text-secondary)",
    transition: "background 0.2s",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  label: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--text-tertiary)",
  },
  addressDisplay: {
    padding: "0.75rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
    fontFamily: "monospace",
    fontSize: "0.9rem",
    color: "var(--text-secondary)",
  },
  input: {
    width: "100%",
    padding: "0.75rem",
    fontSize: "1rem",
    border: "2px solid var(--border-light)",
    borderRadius: "8px",
    boxSizing: "border-box",
    transition: "border-color 0.2s",
    fontFamily: "inherit",
    background: "var(--bg-tertiary)",
    color: "var(--text-primary)",
  },
  balanceHint: {
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
    marginTop: "0.25rem",
  },
  formActions: {
    display: "flex",
    gap: "0.75rem",
    justifyContent: "flex-end",
    marginTop: "0.5rem",
  },
  receiveContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.5rem",
    padding: "1rem 0",
  },
  qrCodeContainer: {
    background: "white",
    padding: "1rem",
    borderRadius: "12px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  qrCode: {
    display: "block",
    width: "200px",
    height: "200px",
  },
  receiveAddress: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  receiveLabel: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--text-tertiary)",
  },
  receiveAddressRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.75rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
  },
  receiveAddressText: {
    flex: 1,
    fontFamily: "monospace",
    fontSize: "0.9rem",
    color: "var(--text-primary)",
    wordBreak: "break-all",
  },
  discoveryContent: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  searchContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  discoveryList: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  discoveryCard: {
    background: "var(--bg-tertiary)",
    padding: "1rem",
    borderRadius: "8px",
    border: "1px solid var(--border-light)",
    color: "var(--text-primary)",
  },
  discoveryCardHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginBottom: "0.5rem",
  },
  discoveryCardInfo: {
    flex: 1,
  },
  discoveryResourceUrl: {
    fontFamily: "monospace",
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "var(--text-primary)",
    marginBottom: "0.25rem",
    wordBreak: "break-all",
  },
  discoveryDescription: {
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
  },
  discoveryCardActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    alignItems: "center",
  },
  badge: {
    fontSize: "0.75rem",
    fontWeight: 600,
    padding: "0.25rem 0.5rem",
    borderRadius: "4px",
    background: "var(--bg-hover)",
    color: "var(--text-tertiary)",
  },
  discoveryCardDetails: {
    marginTop: "1rem",
    paddingTop: "1rem",
    borderTop: "1px solid var(--border-light)",
  },
  discoveryCardSubtitle: {
    margin: "0 0 0.5rem 0",
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  discoveryTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.875rem",
  },
  assetCell: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  payButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.875rem",
    background: "#0052FF",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
    transition: "background 0.2s, transform 0.1s",
  },
  errorText: {
    color: "var(--error-text)",
    padding: "0.5rem",
    background: "var(--error-bg)",
    borderRadius: "4px",
    marginBottom: "0.5rem",
  },
  paymentInfo: {
    padding: "0.75rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
    fontSize: "0.875rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    color: "var(--text-primary)",
  },
  resultContainer: {
    marginTop: "1rem",
    padding: "1rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
    color: "var(--text-primary)",
  },
  resultHeader: {
    fontWeight: 600,
    marginBottom: "0.5rem",
  },
  paymentResult: {
    padding: "0.5rem",
    background: "#e8f5e9",
    borderRadius: "4px",
    marginBottom: "0.5rem",
    fontSize: "0.875rem",
  },
  resultData: {
    marginTop: "0.5rem",
    maxHeight: "200px",
    overflow: "auto",
    fontFamily: "monospace",
    fontSize: "0.875rem",
  },
  mobilePaymentCard: {
    background: "var(--bg-secondary)",
    padding: "1rem",
    borderRadius: "8px",
    border: "1px solid var(--border-light)",
    marginBottom: "0.75rem",
    color: "var(--text-primary)",
  },
  mobileCardRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.5rem 0",
    borderBottom: "1px solid var(--border-light)",
  },
  directCallerCard: {
    background: "var(--bg-secondary)",
    padding: "clamp(1rem, 3vw, 1.5rem)",
    borderRadius: "16px",
    boxShadow: "0 4px 12px var(--shadow)",
    border: "1px solid var(--border-light)",
    color: "var(--text-primary)",
  },
  hintText: {
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
    marginTop: "0.25rem",
    fontStyle: "italic",
  },
  schemaContainer: {
    marginTop: "1rem",
    padding: "1rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
    border: "1px solid var(--border-light)",
    color: "var(--text-primary)",
  },
  schemaTitle: {
    margin: "0 0 0.75rem 0",
    fontSize: "1rem",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  schemaContent: {
    fontSize: "0.875rem",
    color: "var(--text-primary)",
  },
  acceptsList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  acceptItem: {
    padding: "0.75rem",
    background: "var(--bg-secondary)",
    borderRadius: "8px",
    border: "1px solid var(--border-light)",
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    color: "var(--text-primary)",
  },
  outputSchemaContainer: {
    marginTop: "0.5rem",
    paddingTop: "0.5rem",
    borderTop: "1px solid var(--border-light)",
  },
  schemaPreview: {
    marginTop: "0.5rem",
    padding: "0.75rem",
    background: "var(--bg-secondary)",
    borderRadius: "4px",
    fontSize: "0.75rem",
    overflow: "auto",
    maxHeight: "200px",
    fontFamily: "monospace",
    color: "var(--text-primary)",
  },
  schemaDetails: {
    marginTop: "0.5rem",
  },
  pagination: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "2rem",
    paddingTop: "1.5rem",
    borderTop: "1px solid var(--border-color)",
    flexWrap: "wrap",
    gap: "1rem",
  },
  paginationInfo: {
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
  },
  paginationControls: {
    display: "flex",
    gap: "0.75rem",
  },
  filterRow: {
    display: "flex",
    gap: "1rem",
    alignItems: "center",
    flexWrap: "wrap",
  },
  filterLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
  },
  paymentList: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  paymentCard: {
    background: "var(--bg-secondary)",
    padding: "1rem",
    borderRadius: "12px",
    border: "1px solid var(--border-light)",
    color: "var(--text-primary)",
  },
  paymentHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "0.75rem",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  paymentAmount: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  paymentAmountValue: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#ef4444",
  },
  paymentChain: {
    fontSize: "0.75rem",
    padding: "0.25rem 0.5rem",
    background: "var(--bg-tertiary)",
    borderRadius: "4px",
    textTransform: "uppercase",
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  paymentDate: {
    fontSize: "0.875rem",
    color: "var(--text-secondary)",
  },
  paymentDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginTop: "0.75rem",
    paddingTop: "0.75rem",
    borderTop: "1px solid var(--border-light)",
  },
  paymentDetailRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
  },
  paymentDetailLabel: {
    fontWeight: 600,
    color: "var(--text-secondary)",
    minWidth: "100px",
  },
  paymentDetailValue: {
    color: "var(--text-primary)",
  },
  paymentTxHash: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  paymentLink: {
    color: "#0052FF",
    textDecoration: "none",
    fontFamily: "monospace",
    fontSize: "0.875rem",
  },
  paymentBazaarInfo: {
    padding: "0.75rem",
    background: "var(--bg-tertiary)",
    borderRadius: "8px",
    marginBottom: "0.75rem",
    border: "1px solid var(--border-light)",
  },
  paymentBazaarLabel: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#00D4A1",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "0.5rem",
  },
  paymentBazaarContent: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  paymentBazaarDescription: {
    fontSize: "0.875rem",
    color: "var(--text-primary)",
    fontStyle: "italic",
  },
  paymentBazaarType: {
    fontSize: "0.75rem",
    color: "var(--text-secondary)",
    fontWeight: 500,
  },
  payAgainButton: {
    marginTop: "0.75rem",
    padding: "0.5rem 1rem",
    fontSize: "0.875rem",
    background: "#0052FF",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 600,
    transition: "background 0.2s, transform 0.1s",
  },
};

